name: Add to project

on:
  issues:
    types:
      - opened

jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - uses: actions/add-to-project@v1.0.2
        with:
          project-url: https://github.com/orgs/dandi-cache/projects/1
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
